#!/usr/bin/env python3
"""Own the README's generated top: the "At a glance" block and the list of generations
(Publication Standard v1 §8; presentation plan §9.4, finding F04).

Two blocks, each between its own markers, are generated from the registry
(`delu_forecast.registry`) and the claim layer (`delu_forecast.research_claims`), so the README
cannot carry a name, status or number the page does not:

* `<!-- glance:start -->` … `<!-- glance:end -->`, directly under the title: what the project is,
  the headline block (identical to the page's), the terms it introduces, and the demo, the
  report, the evidence and -- once verified -- the MLflow experiment.
* `<!-- research:start -->` … `<!-- research:end -->`: the generations, newest first, each under
  its registry name with its dated status, result, limitations and evidence; then the branches
  that were not adopted.

Everything after them is stable hand-written material (v1's engineering record, setup) that
states no current status. `scripts/cp3_readme.py` keeps its own span.

    uv run python scripts/readme_research.py            # rewrite both blocks in README.md
    uv run python scripts/readme_research.py --check    # exit 1 if either block is stale

The generator fails, rather than guessing, if a marker is missing or appears more than once. Its
one-time migration replaces the hand-written top (v1's "30-second read", which now lives under
v1's heading) with the glance markers; that is the only edit it ever makes outside them.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from delu_forecast import registry as G  # noqa: E402
from delu_forecast import research as R  # noqa: E402
from delu_forecast import research_claims as RC  # noqa: E402
from delu_forecast.claims import (  # noqa: E402
    EXCHANGEABILITY,
    GITHUB_URL,
    HOLDOUT_LIMITATION,
    PAGES_URL,
    SPACE_URL,
    build_claims,
    limitation_bullets,
)

README_PATH = ROOT / "README.md"
GLANCE_START = "<!-- glance:start -->"
GLANCE_END = "<!-- glance:end -->"
START = "<!-- research:start -->"
END = "<!-- research:end -->"
GENERATED = "<!-- Generated by scripts/readme_research.py from the registry and the claim layer. Do not edit by hand. -->"
TITLE = "# DE-LU Day-Ahead Price Forecasting"

#: v1's "30-second read", moved under v1's heading (standard §8). Stable text about the released
#: model; the numbers and statuses it needs come from the claim set and the registry.
V1_READ = (
    "**What it is (30-second read).** A probabilistic forecasting tool that forecasts the next delivery day's "
    "hourly German–Luxembourg (DE-LU) day-ahead electricity price, with calibrated 50 / 80 / 95 % prediction "
    "intervals.",
    "- **Problem** — forecast the next delivery day's hourly DE-LU prices at the 12:00 CET day-ahead gate — "
    "normally 24 values, 23/25 on DST-transition days — across a three-regime market (the 2021–23 energy crisis, "
    "the negative-price/solar era, and Dunkelflaute scarcity).",
    "- **Approach** — a single LightGBM nine-quantile ensemble, CQR-calibrated with isotonic monotonicity last; "
    "walk-forward CV with a one-delivery-day embargo and pinned three-regime folds; **strict-gate features "
    "only** — the shipped model uses no input published after the gate (the day-ahead wind/solar forecast is "
    "measured in a separate post-gate benchmark, never shipped).",
    "- **Feature catalog** — frozen before fitting. Calendar and regime features, the day-ahead load forecast, "
    "calendar-day-matched price lags and D-1-frozen rolling statistics, plus one candidate domain feature: a "
    "residual-load proxy built from a 42-day trailing mean of actual wind and solar generation ending at D-2. Two "
    "catalogs, one comparison, and the shipped one is named in the report — including when the domain feature "
    "does not earn its place.",
    "- **Results** — LightGBM vs. similar-day-naïve / 168h-naïve / Ridge, with five-fold DM labeled "
    "**development / post-selection**, plus **one pre-specified evaluation on a 90-day holdout** the model never "
    "saw — reported once, whatever it says, and labeled *confirmatory-style, not power-qualified*. Three-stage "
    "reliability, SHAP, permutation importance, and regime-stratified errors. A separate one-number benchmark "
    "measures what the post-gate wind/solar forecast would have been worth.",
    "- **Honest limitations** — regime-shift exchangeability; two disclosed assumptions (the load forecast's "
    "pre-gate availability, and revision in the actual-generation archive); the negative-price floor; and model "
    "staleness, with **four cutoffs published separately** — snapshot, raw-model fit, final calibration, and "
    "holdout. The shipped model is exactly the model the holdout evaluated: there is no retrain after the result "
    "is opened.",
    "- **Demo & reproduction** — the report on GitHub Pages is the primary link; the in-browser demo is one "
    "labeled click deeper, and what it renders over the holdout period is a **historical out-of-sample "
    "replay**, not a live forecast; `make train` after checking out the tagged commit reproduces the champion "
    "from the committed snapshot. The release is **frozen**: there is no scheduled refresh. Publication is "
    "owner-only — see [`docs/deploy.md`](docs/deploy.md).",
    "",
    "v1 was built in four checkpoints: data and features (CP-1), model and analysis (CP-2), showcase and release "
    "(CP-3), then browser execution (CP-3B); its plan is **[v6.8](capstone_V6_8.md)**, and its engineering "
    "record follows the generations below.",
)


class MarkerError(RuntimeError):
    pass


def md(template_key: str) -> str:
    return RC.render(template_key, "md", surface=RC.README)


def token(template: str, claim: str = "P23") -> str:
    return RC.render_template(claim, template, "md")


def audit_links(checkpoint_code: str, *, source: str | None = None, line: int | None = None) -> str:
    """Audit-grade evidence (standard §7): each "<type>, frozen <date>", at its evidence tag."""
    checkpoint = G.CHECKPOINTS[checkpoint_code]
    tag, date = checkpoint.evidence_tag, G.EVIDENCE_TAGS[checkpoint.evidence_tag][1]
    items = [("Engineering report", checkpoint.report, None), ("Review verdict", checkpoint.verdict, None)]
    if source:
        items.append(("Raw CSV rows", source, line))
    links = [f"[{kind}, frozen {date}]({GITHUB_URL}/blob/{tag}/{path}{f'#L{row}' if row else ''})"
             for kind, path, row in items]
    return "Evidence: " + " · ".join(links)


def mlflow_route(route: str) -> str | None:
    import json

    index = ROOT / "reports" / "presentation" / "mlflow_index.json"
    if not index.is_file():
        return None
    return json.loads(index.read_text()).get("routes", {}).get(route, {}).get("url")


def build_glance(target: str = "md") -> str:
    """The "At a glance" block. `target="html"` renders the same content with its bindings, so the
    publication lint can read the README's reading path exactly as it reads the page's."""
    released = G.released()
    experiment = mlflow_route("experiment")
    html = target == "html"

    def render(key: str) -> str:
        return RC.render(key, target, surface=RC.README)

    def tok(template: str, claim: str = "P23") -> str:
        return RC.render_template(claim, template, target)

    def bold(text: str) -> str:
        return f"<strong>{text}</strong>" if html else f"**{text}**"

    def link(text: str, url: str) -> str:
        return f'<a href="{url}">{text}</a>' if html else f"[{text}]({url})"

    def para(text: str) -> str:
        return f"<p>{text}</p>" if html else text

    terms = [render(key) for key in RC.headline_terms()]
    body = [
        f"<h2>At a glance</h2>" if html else "## At a glance",
        "",
        para(bold("What it is.") + " Probabilistic forecasts of the next day's hourly German–Luxembourg (DE-LU) "
             "day-ahead electricity price, with prediction intervals, and the record of how successive research "
             "models were compared and checked."),
        "",
        para(bold(f"Research, {tok('{g:current.name}')}.") + " " + RC.headline(target)),
        "",
        ("<ul>" + "".join(f"<li>{term}</li>" for term in terms) + "</ul>") if html
        else "\n".join(f"- {term}" for term in terms),
        "",
        para(bold(f"Demo, {tok('{g:released.name}')}:") + " " + link(f"try the {tok('{g:released.version}')} demo", SPACE_URL)
             + ". " + tok("{g:release_rule}", "P22")),
        "",
        para(bold("How the product works:") + " " + render("product.lede") + " "
             + link("Read it in the report", PAGES_URL + "#product") + ": its data, validation, results, failures, "
             "interval reliability and how to run it."),
        "",
        para(bold("Report:") + " " + link("the one-page report", PAGES_URL) + ", with every result, its limits and its evidence."),
        "",
        para(bold("Evidence:") + " each generation below links its engineering report, its review verdict and its "
             "source rows, frozen at its evidence tag."),
    ]
    if experiment:
        body += ["", para(bold("MLflow:") + " " + link("the <code>delu-generations</code> experiment" if html
                                                     else "the `delu-generations` experiment", experiment)
                          + ", mirrored from the committed evidence; the repository is the source of truth.")]
    if html:
        return "\n".join(line for line in body if line)
    return "\n".join([GLANCE_START, GENERATED, "", *body, "", GLANCE_END])


def not_established(keys: tuple[str, ...]) -> list[str]:
    return ["**What this result does not establish:**", "", *[f"- {md(key)}" for key in keys], ""]


def transition_lines(entry: G.Entry) -> list[str]:
    """The adopted transition into this generation (PUBLISH_RULES 1.0 A3), as on the page: what changed, the
    comparator set in advance, the result and, where the comparator is not the predecessor, why no paired
    predecessor comparison exists. Its limits are the section's own list below."""
    item = G.transition_into(entry)
    if item is None:
        return []
    key = f"transition.{item.id}"
    lines = [f"**{md(f'{key}.title')}.**", ""]
    for name, label in (("change", "What changed"), ("comparator", "Comparator"), ("result", "Result"),
                        ("predecessor", "Against the predecessor")):
        if f"{key}.{name}" in RC.BLOCKS_BY_KEY:
            lines.append(f"- **{label}.** {md(f'{key}.{name}')}")
    return lines + [""]


def generation_section(entry: G.Entry) -> list[str]:
    head = [f"### {entry.name}", "", f"*{entry.subtitle}.* {G.status_sentence(entry)}", ""]
    if entry.id == "v4":
        primary = R.get("cp21.uncertainty.HGL-HG.equal_fold.MAE")
        return head + [
            *transition_lines(entry),
            md("v4.outcome.head"), "",
            f"- {md('v4.outcome.mae')}.",
            f"- {md('v4.outcome.wis')}.",
            "",
            md("v4.rule"), "",
            md("v4.reading"), "",
            *not_established(("v4.caveat.blocks", "v4.caveat.peak", "v4.caveat.class")),
            md("v4.decision"), "",
            audit_links("CP-21", source=primary.source_path, line=primary.source_line), "",
        ]
    if entry.id == "v3":
        return head + [
            *transition_lines(entry),
            md("v3.outcome.head"), "",
            f"- {md('v3.outcome.mae')}.",
            f"- {md('v3.outcome.wis')}.",
            "",
            md("v3.reading"), "",
            *not_established(("v3.caveat.bundle", "v3.caveat.fold3", "v3.caveat.class")),
            md("v3.decision"), "",
            audit_links("CP-20", source="reports/weather-ablation/uncertainty.csv", line=12), "",
        ]
    if entry.id == "v2":
        return head + [
            *transition_lines(entry),
            md("v2.result.hb2"), "",
            md("v2.result.hp"), "",
            *not_established(("v2.caveat.attribution", "v2.caveat.split", "v2.caveat.class")),
            md("v2.decision"), "",
            audit_links("CP-16", source="reports/v2-causal/uncertainty.csv", line=32), "",
        ]
    if entry.id == "v1":
        C = build_claims()
        return head + [
            *V1_READ, "",
            md("v1.what"), "",
            md("v1.holdout"), "",
            f"> {C['holdout_dm_label']}", "",
            md("v1.unflattering"), "",
            md("v1.lesson"), "",
            "#### v1's limitations", "",
            "§7.1 of v1's plan requires this paragraph verbatim, and the surfaces must agree:", "",
            f"> {HOLDOUT_LIMITATION}", "",
            "§6.2 requires this one verbatim, for the same reason:", "",
            f"> {EXCHANGEABILITY}", "",
            "The complete set, rendered from one place onto every surface that presents v1:", "",
            *[f"- {bullet}" for bullet in limitation_bullets(C)],
            "",
            f"And one on the environment: {C['floor_change']}",
            "",
        ]
    raise MarkerError(f"no README section for the generation {entry.id}")


def branch_section(entry: G.Entry) -> list[str]:
    return [
        f"#### {entry.name}", "",
        f"*{entry.subtitle}.* {G.status_sentence(entry)}", "",
        f"{md(f'branch.{entry.id}.question')} {md(f'branch.{entry.id}.result')} {md(f'branch.{entry.id}.reason')}", "",
        audit_links(entry.checkpoint), "",
    ]


def build_block() -> str:
    lines = [
        START,
        GENERATED,
        "",
        "## Generations, newest first",
        "",
        f"Names and statuses come from the registry. The research results are development evidence after "
        f"selection, on the same historical hours for every policy; the released model's one-shot holdout is a "
        f"separate evidence class. The [report]({PAGES_URL}#chapters) has the charts and the values.",
        "",
    ]
    for entry in G.generations(newest_first=True):
        lines += generation_section(entry)
    # Rejected branches, grouped where they sit in the lineage and headed apart from the adopted transitions (A3).
    groups: dict[str, list[G.Entry]] = {}
    for entry in G.branches():
        node = entry
        while node.kind != "generation":
            node = G.get(node.after)
        groups.setdefault(node.id, []).append(entry)
    for generation in G.generations():
        if generation.id not in groups:
            continue
        later = next((item.successor for item in G.transitions() if item.predecessor.id == generation.id), None)
        span = f"between {generation.version} and {later.version}" if later else f"after {generation.version}"
        lines += [f"### Experiments not adopted {span}", ""]
        for entry in groups[generation.id]:
            lines += branch_section(entry)
    lines += [
        "### Reading the comparison", "",
        *[f"- {md(key)}" for key in RC.comparison_terms()],
        *([""] if RC.comparison_terms() else []),
        RC.target_sentence("md", surface=RC.README), "",
        md("overview.fairness.readme"), "",
        md("comparison.finding") + " " + md("comparison.caveat"), "",
        md("comparison.scale"), "",
        md("overview.f07"), "",
        "### Further reading", "",
        "- The research updates behind each generation: [CP-20](docs/track-b/research-content/cp20-update.md) and "
        "[CP-15 and CP-16](docs/track-b/research-content/cp15-cp16-update.md).",
        "- The landing records: [CP-21](docs/track-b/cp-21-landing-2026-09-30.md), "
        "[CP-20](docs/track-b/cp-20-landing-2026-09-24.md), "
        "[CP-16](docs/track-b/cp-16-landing-2026-09-23.md) and [CP-15](docs/track-b/cp-15-landing.md). CP-3B's "
        "[unmet Integration item](docs/track-b/evidence/cp-3b/item-6-NOT-COMPLETED.md) is disclosed.",
        "- The Owner-managed Hebrew [Q&A record](שאלות%20תשובות.docx) and the "
        "[research memo](docs/track-b/forecasting-research-2026-09-15.md), which is historical motivation, not a "
        "measured result.",
        "",
        END,
    ]
    return "\n".join(lines)


def _span(text: str, start: str, end: str) -> tuple[int, int]:
    starts, ends = text.count(start), text.count(end)
    if starts != 1 or ends != 1:
        raise MarkerError(
            f"README.md must contain each marker exactly once; found {starts} {start!r} and {ends} {end!r}"
        )
    begin, finish = text.index(start), text.index(end) + len(end)
    if finish < begin:
        raise MarkerError(f"{end!r} precedes {start!r}")
    return begin, finish


def migrate(text: str) -> str:
    """Replace the hand-written top (v1's 30-second read, now under v1's heading) with an empty
    glance span directly under the title, once."""
    if GLANCE_START in text or GLANCE_END in text:
        return text
    if not text.startswith(TITLE + "\n") or START not in text:
        raise MarkerError("no glance markers, and no title and research block to migrate from")
    return f"{TITLE}\n\n{GLANCE_START}\n{GLANCE_END}\n\n" + text[text.index(START):]


def apply(text: str) -> str:
    begin, finish = _span(text, GLANCE_START, GLANCE_END)
    text = text[:begin] + build_glance() + text[finish:]
    begin, finish = _span(text, START, END)
    if begin < text.index(GLANCE_END):
        raise MarkerError("the generations block must follow the glance block")
    return text[:begin] + build_block() + text[finish:]


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    parser.add_argument("--check", action="store_true", help="exit 1 if README.md is stale")
    args = parser.parse_args()
    original = README_PATH.read_text()
    updated = apply(migrate(original))
    if args.check:
        if updated != original:
            print("README generated blocks are stale; run scripts/readme_research.py")
            return 1
        print("README generated blocks are current")
        return 0
    README_PATH.write_text(updated)
    print(f"regenerated the glance and generations blocks of {README_PATH}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
