#!/usr/bin/env python3
"""Own the README's research section (presentation plan §9.4, finding F04).

The section between `<!-- research:start -->` and `<!-- research:end -->` is generated from the
same claim templates the page renders (`delu_forecast.research_claims`), so the README cannot
carry a number the page does not. Nothing outside the markers is touched; `scripts/cp3_readme.py`
keeps its own span.

    uv run python scripts/readme_research.py            # rewrite the block in README.md
    uv run python scripts/readme_research.py --check    # exit 1 if the block is stale

The generator fails, rather than guessing, if either marker is missing or appears more than once.
The first run replaces the hand-written "Current development" section with the markers; that
migration is the only edit this script ever makes outside them.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from delu_forecast.claims import PAGES_URL  # noqa: E402
from delu_forecast.research_claims import README, README_BLOCKS, render  # noqa: E402

README_PATH = ROOT / "README.md"
START = "<!-- research:start -->"
END = "<!-- research:end -->"

#: The hand-written section this generator replaced (plan §8.7), recognized only for the one-time
#: migration: from its heading up to the next top-level section.
LEGACY_HEADING = "## Current development — 2026-09-16"
LEGACY_NEXT = "## CP-1 data and fixed features"


class MarkerError(RuntimeError):
    pass


def build_block() -> str:
    paragraphs = [render(key, "md", surface=README) for key in README_BLOCKS]
    by_key = dict(zip(README_BLOCKS, paragraphs))
    return "\n".join(
        [
            START,
            "<!-- Generated by scripts/readme_research.py from src/delu_forecast/research_claims.py."
            " Do not edit by hand. -->",
            "",
            "## Research since v1: development evidence, post-selection",
            "",
            "**v1 is the released product and the model the demo runs. v3 is the current research"
            " model.** Every result below is development evidence after selection, on the same"
            f" historical hours for every policy. The [report]({PAGES_URL}#journey) has the charts.",
            "",
            by_key["opening.summary"],
            "",
            "### v3 · weather features (CP-20)",
            "",
            by_key["v3.change"],
            "",
            by_key["v3.outcome.head"],
            "",
            f"- {by_key['v3.outcome.mae']}.",
            f"- {by_key['v3.outcome.wis']}.",
            "",
            by_key["v3.result"],
            "",
            f"- {by_key['v3.caveat.bundle']}",
            f"- {by_key['v3.caveat.fold3']}",
            "",
            "### v2 · blended LEAR, hour-aware intervals (CP-16), and the road to it",
            "",
            by_key["v2.branch.cp10"],
            "",
            by_key["v2.result.hb2"],
            "",
            by_key["v2.result.hp"],
            "",
            "### Reading the comparison",
            "",
            by_key["overview.fairness.readme"],
            "",
            by_key["overview.f07"],
            "",
            "### Evidence",
            "",
            "- CP-20: [update](docs/track-b/research-content/cp20-update.md) ·"
            " [claim map](docs/track-b/research-content/cp20-claims.md) ·"
            " [report](reports/weather-ablation/report.md) ·"
            " [Integration review](docs/track-b/evidence/cp-20/integration.md) ·"
            " [landing record](docs/track-b/cp-20-landing-2026-09-24.md)",
            "- CP-15 and CP-16: [update](docs/track-b/research-content/cp15-cp16-update.md) ·"
            " [claim map](docs/track-b/research-content/cp15-cp16-claims.md) ·"
            " [CP-15 review](docs/track-b/evidence/cp-15/integration.md) ·"
            " [CP-16 review](docs/track-b/evidence/cp-16/integration.md)",
            "- CP-10: [report](reports/cp10/report.md). CP-3B's"
            " [unmet Integration item](docs/track-b/evidence/cp-3b/item-6-NOT-COMPLETED.md)"
            " remains disclosed.",
            "- The Owner-managed Hebrew [Q&A record](שאלות%20תשובות.docx) and the"
            " [research memo](docs/track-b/forecasting-research-2026-09-15.md), which is historical"
            " motivation, not a measured result.",
            "",
            END,
        ]
    )


def _span(text: str) -> tuple[int, int]:
    starts, ends = text.count(START), text.count(END)
    if starts != 1 or ends != 1:
        raise MarkerError(
            f"README.md must contain each research marker exactly once; found {starts} "
            f"{START!r} and {ends} {END!r}"
        )
    begin, finish = text.index(START), text.index(END) + len(END)
    if finish < begin:
        raise MarkerError("the research end marker precedes the start marker")
    return begin, finish


def migrate(text: str) -> str:
    """Replace the legacy hand-written section with an empty marked span, once."""
    if START in text or END in text:
        return text
    if LEGACY_HEADING not in text or LEGACY_NEXT not in text:
        raise MarkerError("no research markers and no legacy section to replace")
    head, _, rest = text.partition(LEGACY_HEADING)
    _, _, tail = rest.partition(LEGACY_NEXT)
    return f"{head}{START}\n{END}\n\n{LEGACY_NEXT}{tail}"


def apply(text: str) -> str:
    begin, finish = _span(text)
    return text[:begin] + build_block() + text[finish:]


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    parser.add_argument("--check", action="store_true", help="exit 1 if README.md is stale")
    args = parser.parse_args()
    original = README_PATH.read_text()
    updated = apply(migrate(original))
    if args.check:
        if updated != original:
            print("README research block is stale; run scripts/readme_research.py")
            return 1
        print("README research block is current")
        return 0
    README_PATH.write_text(updated)
    print(f"regenerated the research block of {README_PATH}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
